runtime: python27
api_version: 1
threadsafe: true

# [START handlers]
handlers:
- url: /
  script: main.app

- url: /templates/home.html
  script: main.app

#- url: /templates
#  static_dir: templates

- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /.*
  script: main.app
# [END handlers]

# [START] libraries
libraries:
- name: flask
  version: 0.12
# [END] libraries